### ISSUE TITLE
dQ values being misleadingly reported

### ISSUE THREAD

**Issue by smk78** [SasView/sasdata#66]
This may be a non-issue, it depends what version of sasdata the Github actions 6.0.0 build I'm using (8437842248) uses. But I figure it's better to report this because it's potentially a big problem.

When I load any of the AOT microemulsion example datasets the FitPage is reporting "Smearing: Use dQ data". Only dQ in these datasets is zero! v5.x reports these datasets as "Smearing: None".

In the Resolution tab the fact that the actual dQ is zero is being correctly reported
![image](https://github.com/SasView/sasdata/assets/10938679/b691a81e-9da6-4cba-a7f8-672cb7cd5d2d)

But it's not clear to me how the program would use values of dQ=0; isn't that like infinitely good resolution? :-)

So I think this is hugely misleading as things stand.

But as I say, it may be the build I'm using.

**Comment by krzywon** [comment]
@smk78, thanks for the report. The behavior was different before https://github.com/SasView/sasview/pull/2828 was merged. The AOT data all have '0' for their dQ values in the data file, which is read in as-is by `sasdata`. SasView has sanity checks for handling data with unrealistic dQ values when giving options for fitting, but the PR changed some of those checks.

I think this issue should be in the SasView repository, because it is GUI behavior that is faulty.
